version: '3'

services:
    app:
        build: 
            dockerfile: ./services/app/Dockerfile
            context: .
        command: uwsgi
        ports:
            - "${APP_PORT}:${APP_PORT}"
            - "8001:8001"
        expose:
            - ${APP_PORT}
        env_file:
            - .env
        depends_on: 
            - ${POSTGRES_DOCKER_HOST}
        links: 
            - ${POSTGRES_DOCKER_HOST}:${POSTGRES_DOCKER_HOST}
        volumes:
            - ./staticfiles:/usr/src/app/staticfiles
            - ./media:/usr/src/app/media

    postgres:
        image: postgres:12.1
        hostname: ${POSTGRES_DOCKER_HOST}
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        env_file:
            - .env
        volumes:
            - ./postgres/data:/var/lib/postgresql/data

    nginx:
        restart: unless-stopped
        image: staticfloat/nginx-certbot
        ports:
            - 80:80/tcp
            - 443:443/tcp
        environment:
            ENVSUBST_VARS: FQDN
        depends_on:
            - app
        links:
            - app:app
        volumes:
            - ./services/nginx/conf.d:/etc/nginx/user.conf.d:ro
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
            - letsencrypt:/etc/letsencrypt
            - ./media:/media
            - ./staticfiles:/static
        env_file:
            - .env
volumes:
    letsencrypt:
