version: '3'

services:
    app:
        build: 
            dockerfile: ./services/app/Dockerfile
            context: .
        command: uwsgi
        ports:
            - "${APP_PORT}:${APP_PORT}"
            - "8001:8001"
        expose:
            - ${APP_PORT}
        env_file:
            - .env
        depends_on: 
            - ${POSTGRES_DOCKER_HOST}
        links: 
            - ${POSTGRES_DOCKER_HOST}:${POSTGRES_DOCKER_HOST}
        volumes:
            - ./staticfiles:/usr/src/app/staticfiles
            - ./media:/usr/src/app/media

    postgres:
        image: postgres:12.1
        hostname: ${POSTGRES_DOCKER_HOST}
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        env_file:
            - .env
        volumes:
            - ./postgres/data:/var/lib/postgresql/data

    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - URL=${FQDN}
            - SUBDOMAINS=${SUBDOMAIN},
            - VALIDATION=http
            - EMAIL=${CERTBOT_EMAIL}
        volumes:
            - ./staticfiles:/static
            - ./media:/media
            - ./data/letsencrypt:/config
            - ./services/nginx/conf.d/:/config/nginx/site-confs/
        ports:
            - 443:443
            - 80:80
        restart: unless-stopped
        env_file: 
            - .env
        depends_on:
            - app
        links:
            - app:app
