version: '3'

services:
    app:
        build: 
            dockerfile: ./services/app/Dockerfile
            context: .
        command: uwsgi
        ports:
            - "8000:8000"
            - "8001:8001"
        env_file: 
            .env
        depends_on: 
            - ${POSTGRES_DOCKER_HOST}
        links: 
            - ${POSTGRES_DOCKER_HOST}:${POSTGRES_DOCKER_HOST}
        volumes: 
            - ./staticfiles:/usr/src/app/staticfiles


    postgres:
        image: postgres:12.1
        hostname: ${POSTGRES_DOCKER_HOST}
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        env_file:
            - .env
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
    
    nginx:
        build: 
            dockerfile: ./services/nginx/Dockerfile
            context: .
        ports: 
            - 80:80
        depends_on: 
            - app
        links: 
            - app:app
        volumes: 
            - ./media:/media
            - ./staticfiles:/static